use crate::model::*;
use {CategoryId::*, ItemId::*, RarityId::*};

#[derive(Debug)]
pub enum SurvivorId {
    Commando,
    Huntress,
    Bandit,
    MulT,
    Engineer,
    Artificer,
    Mercenary,
    Rex,
    Loader,
    Acrid,
    Captain,
    Railgunner,
    VoidFiend,
    Heretic,
}

#[derive(Debug)]
pub enum MonsterId {
    AlloyVulture,
    AlphaConstruct,
    Beetle,
    BeetleGuard,
    BighornBison,
    BlindPest,
    BlindVermin,
    BrassContraption,
    ClayApothecary,
    ClayTemplar,
    ElderLemurian,
    Geep,
    Gip,
    GreaterWisp,
    Gup,
    HermitCrab,
    Imp,
    Jellyfish,
    Larva,
    Lemurian,
    LesserWisp,
    LunarExploder,
    LunarGolem,
    LunarWisp,
    MiniMushrum,
    Parent,
    SolusProbe,
    StoneGolem,
    VoidBarnacle,
    VoidJailer,
    VoidReaver,
    BeetleQueen,
    ClayDunestrider,
    Grandparent,
    Grovetender,
    ImpOverlord,
    MagmaWorm,
    OverloadingWorm,
    Scavenger,
    SolusControlUnit,
    StoneTitan,
    VoidDevastator,
    WanderingVagrant,
    XiConstruct,
    HealingCore,
    MalachiteUrchin,
    Newt,
    VoidInfestor,
    AlloyWorshipUnit,
    ArtifactReliquary,
    Aurelionite,
    GuraguraTheLucky,
    KipkipTheGentle,
    Mithrix,
    TwiptwipTheDevotee,
    Voidling,
    WipwipTheWild,
    AlphaConstructAlly,
    AurelioniteAlly,
    BeetleGuardAlly,
    VoidDevastatorAlly,
    VoidJailerAlly,
    VoidReaverAlly,
}

#[derive(Debug)]
pub enum RarityId {
    /// Common
    White,
    /// Uncommon
    Green,
    /// Legendary
    Red,
    /// Boss
    Yellow,
    /// Lunar
    Blue,
    /// Void
    Purple,
    /// Equipment
    Orange,
}

#[derive(Debug)]
pub enum CategoryId {
    Damage,
    Healing,
    Utility,
    BrotherBlacklist,
    OnKillEffect,
}

#[derive(Debug, PartialEq, Eq)]
pub enum ItemId {
    SoldiersSyringe,
    TougherTimes,
    MonsterTooth,
    LensMakersGlasses,
    PaulsGoatHoof,
    BustlingFungus,
    Crowbar,
    TriTipDagger,
    Warbanner,
    CautiousSlug,
    PersonalShieldGenerator,
    Medkit,
    Gasoline,
    StunGrenade,
    BundleOfFireworks,
    EnergyDrink,
    BackupMagazine,
    StickyBomb,
    RustedKey,
    ArmorPiercingRounds,
    TopazBrooch,
    FocusCrystal,
    BisonSteak,
    RepulsionArmorPlate,
    Mocha,
    PowerElixir,
    DelicateWatch,
    OddlyShapedOpal,
    RollOfPennies,
    ItemScrapWhite,
    ATGMissileMk1,
    WillOTheWisp,
    HopooFeather,
    Ukulele,
    LeechingSeed,
    PredatoryInstincts,
    RedWhip,
    OldWarStealthkit,
    HarvestersScythe,
    FuelCell,
    Infusion,
    Bandolier,
    BerzerkersPauldron,
    RoseBuckler,
    RunaldsBand,
    KjarosBand,
    Chronobauble,
    WaxQuail,
    OldGuillotine,
    WarHorn,
    LeptonDaisy,
    Razorwire,
    GhorsTome,
    SquidPolyp,
    DeathMark,
    HuntersHarpoon,
    IgnitionTank,
    Shuriken,
    RegeneratingScrap,
    ShippingRequestForm,
    ItemScrapGreen,
    BrilliantBehemoth,
    CeremonialDagger,
    FrostRelic,
    HappiestMask,
    H3AD5Tv2,
    NkuhanasOpinion,
    UnstableTeslaCoil,
    FiftySevenLeafClover,
    SentientMeatHook,
    AlienHead,
    SoulboundCatalyst,
    DiosBestFriend,
    HardlightAfterburner,
    WakeOfVultures,
    Brainstalks,
    RejuvenationRack,
    Aegis,
    ShatteringJustice,
    ResonanceDisc,
    InterstellarDeskPlant,
    DefensiveMicrobots,
    LaserScope,
    PocketICBM,
    SpareDroneParts,
    SymbioticScorpion,
    BensRaincoat,
    BottledChaos,
    ItemScrapRed,
    TitanicKnurl,
    QueensGland,
    HalcyonSeed,
    LittleDisciple,
    Pearl,
    IrradiantPearl,
    GenesisLoop,
    ArtifactKey,
    MoltenPerforator,
    Shatterspleen,
    MiredUrn,
    ChargedPerforator,
    EmpathyCores,
    Planula,
    DefenseNucleus,
    ItemScrapYellow,
    BenthicBloom,
    EncrustedKey,
    LostSeersLenses,
    LysateCell,
    Needletick,
    NewlyHatchedZoea,
    PlasmaShrimp,
    PluripotentLarva,
    Polylute,
    SaferSpaces,
    SingularityBand,
    Tentabauble,
    VoidsentFlame,
    WeepingFungus,
    ShapedGlass,
    BrittleCrown,
    Transcendence,
    Corpsebloom,
    GestureOfTheDrowned,
    StridesOfHeresy,
    VisionsOfHeresy,
    BeadsOfFealty,
    FocusedConvergence,
    DefiantGouge,
    MercurialRachis,
    Purity,
    HooksOfHeresy,
    Egocentrism,
    EulogyZero,
    StoneFluxPauldron,
    LightFluxPauldron,
    EssenceOfHeresy,
    GlowingMeteorite,
    HelfireTincture,
    EffigyOfGrief,
    SpinelTonic,
    DisposableMissileLauncher,
    ForeignFruit,
    PrimordialCube,
    TrophyHuntersTricorn,
    OcularHUD,
    TheBackUp,
    PreonAccumulator,
    GooboJr,
    MilkyChrysalis,
    RoyalCapacitor,
    Molotov6Pack,
    ExecutiveCard,
    TheCrowdfunder,
    GnarledWoodsprite,
    RadarScanner,
    EccentricVase,
    BlastShower,
    VolcanicEgg,
    JadeElephant,
    Sawmerang,
    Recycler,
    SuperMassiveLeech,
    GoragsOpus,
    ForgiveMePlease,
    RemoteCaffeinator,
    IfritsDistinction,
    HisReassurance,
    SilenceBetweenTwoStrikes,
    HerBitingEmbrace,
    NkuhanasRetort,
    SpectralCirclet,
    SharedDesign,
    FuelArray,
}

impl From<ItemId> for Item {
    fn from(id: ItemId) -> Self {
        match id {
            SoldiersSyringe => Item {
                id: SoldiersSyringe,
                name: "Soldier's Syringe".into(),
                rarity: White,
                category: vec![Damage],
            },
            TougherTimes => Item {
                id: TougherTimes,
                name: "Tougher Times".into(),
                rarity: White,
                category: vec![Damage, BrotherBlacklist],
            },
            MonsterTooth => Item {
                id: MonsterTooth,
                name: "Monster Tooth".into(),
                rarity: White,
                category: vec![Healing, OnKillEffect],
            },
        }
    }
}

#[derive(Debug)]
pub enum OutcomeId {
    Defeat,
    FateUnknown,
    Victory,
}

#[derive(Debug)]
pub enum DifficultyId {
    Drizzle,
    Rainstorm,
    Monsoon,
    Eclipse1,
    Eclipse2,
    Eclipse3,
    Eclipse4,
    Eclipse5,
    Eclipse6,
    Eclipse7,
    Eclipse8,
}

#[derive(Debug)]
pub enum EnvironmentId {
    DistantRoost,
    TitanicPlains,
    SiphonedForest,
    AbandonedAqueduct,
    WetlandAspect,
    AphelianSanctuary,
    RallypointDelta,
    ScorchedAcres,
    SulfurPools,
    AbyssalDepths,
    SirensCall,
    SunderedGrove,
    SkyMeadow,
    Commencement,
    AMomentFractured,
    AMomentWhole,
    BazaarBetweenTime,
    BulwarksAmbry,
    GildedCoast,
    VoidFields,
    VoidLocus,
    ThePlanetarium,
}
