mod data;
mod model;

use chrono::{Duration, TimeZone};
use data::{ItemId::*, *};
use model::*;

fn main() {
    // This takes fucking forever to type in. Please disinfect me.
    let runs = vec![
        Run {
            timestamp: chrono::Utc
                .with_ymd_and_hms(2023, 11, 18, 6, 31, 18)
                .unwrap(),
            difficulty: DifficultyId::Eclipse1,
            players: vec![
                PlayerRun {
                    player_name: "sunrosa".into(),
                    time_alive: mins_secs(81, 24),
                    kills: 684,
                    minion_kills: 57,
                    deaths: 1,
                    damage_dealt: 4_735_102,
                    minion_damage_dealt: 361_520,
                    most_damage_dealt: 10_386,
                    damage_taken: 22_261,
                    highest_level: 27,
                    gold_collected: 263_813,
                    items_collected: 108,
                    stages_completed: 4,
                    purchases: 128,
                    survivor: SurvivorId::MulT,
                    loadout: Some(SurvivorLoadout::MulT(MulTLoadout {
                        primary1: MulTPrimaryId::AutoNailgun,
                        primary2: MulTPrimaryId::AutoNailgun,
                        special: MulTSpecialId::PowerMode,
                    })),
                    killed_by: MonsterId::ElderLemurian,
                    outcome: OutcomeId::Defeat,
                    stages: vec![
                        PlayerStageStats {
                            items: vec![
                                (BackupMagazine, 1),
                                (StunGrenade, 1),
                                (CautiousSlug, 1),
                                (DelicateWatch, 1),
                                (IgnitionTank, 1),
                                (FocusCrystal, 2),
                                (LensMakersGlasses, 1),
                                (SquidPolyp, 1),
                                (BundleOfFireworks, 1),
                                (Gasoline, 1),
                                (OldGuillotine, 1),
                            ],
                            equipment: Some(VolcanicEgg).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (BackupMagazine, 1),
                                (StunGrenade, 1),
                                (CautiousSlug, 1),
                                (DelicateWatch, 1),
                                (IgnitionTank, 1),
                                (FocusCrystal, 2),
                                (LensMakersGlasses, 1),
                                (Gasoline, 1),
                                (SoldiersSyringe, 1),
                                (ATGMissileMk1, 3),
                                (RepulsionArmorPlate, 2),
                                (MiredUrn, 1),
                                (Ukulele, 1),
                                (SoulboundCatalyst, 1),
                            ],
                            equipment: Some(VolcanicEgg).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (BackupMagazine, 1),
                                (StunGrenade, 2),
                                (CautiousSlug, 1),
                                (DelicateWatch, 2),
                                (IgnitionTank, 1),
                                (LensMakersGlasses, 1),
                                (Gasoline, 1),
                                (SoldiersSyringe, 1),
                                (ATGMissileMk1, 3),
                                (RepulsionArmorPlate, 2),
                                (MiredUrn, 1),
                                (SoulboundCatalyst, 1),
                                (PaulsGoatHoof, 2),
                                (PocketICBM, 1),
                                (Polylute, 2),
                                (RustedKey, 1),
                                (SaferSpaces, 1),
                                (TriTipDagger, 1),
                                (ItemScrapGreen, 4),
                                (ItemScrapWhite, 6),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (StunGrenade, 2),
                                (CautiousSlug, 1),
                                (DelicateWatch, 3),
                                (IgnitionTank, 1),
                                (LensMakersGlasses, 1),
                                (Gasoline, 1),
                                (SoldiersSyringe, 2),
                                (ATGMissileMk1, 4),
                                (RepulsionArmorPlate, 2),
                                (MiredUrn, 1),
                                (SoulboundCatalyst, 1),
                                (PaulsGoatHoof, 2),
                                (PocketICBM, 1),
                                (Polylute, 2),
                                (SaferSpaces, 1),
                                (TriTipDagger, 5),
                                (ItemScrapGreen, 9),
                                (EnergyDrink, 1),
                                (RegeneratingScrap, 1),
                                (ShatteringJustice, 1),
                                (EncrustedKey, 1),
                                (PredatoryInstincts, 1),
                                (DeathMark, 1),
                            ],
                            equipment: Some(DisposableMissileLauncher).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (StunGrenade, 2),
                                (CautiousSlug, 1),
                                (IgnitionTank, 2),
                                (LensMakersGlasses, 1),
                                (Gasoline, 1),
                                (SoldiersSyringe, 2),
                                (ATGMissileMk1, 4),
                                (RepulsionArmorPlate, 2),
                                (MiredUrn, 1),
                                (SoulboundCatalyst, 1),
                                (PaulsGoatHoof, 3),
                                (PocketICBM, 1),
                                (Polylute, 2),
                                (SaferSpaces, 2),
                                (TriTipDagger, 5),
                                (ItemScrapGreen, 9),
                                (EnergyDrink, 1),
                                (RegeneratingScrap, 1),
                                (ShatteringJustice, 1),
                                (EncrustedKey, 1),
                                (PredatoryInstincts, 2),
                                (DeathMark, 1),
                                (LeptonDaisy, 3),
                                (PersonalShieldGenerator, 1),
                                (GhorsTome, 1),
                                (HopooFeather, 1),
                                (Chronobauble, 1),
                                (FocusCrystal, 1),
                                (WillOTheWisp, 1),
                                (EmpathyCores, 1),
                                (OldGuillotine, 1),
                                (Bandolier, 1),
                                (DelicateWatchBroken, 3),
                            ],
                            equipment: Some(DisposableMissileLauncher).into(),
                            died: true,
                        },
                    ],
                },
                PlayerRun {
                    player_name: "Veryveryoriginalname".into(),
                    time_alive: mins_secs(80, 48),
                    kills: 502,
                    minion_kills: 5,
                    deaths: 2,
                    damage_dealt: 3_180_003,
                    minion_damage_dealt: 169_128,
                    most_damage_dealt: 41_250,
                    damage_taken: 51_357,
                    highest_level: 27,
                    gold_collected: 199_976,
                    items_collected: 72,
                    stages_completed: 4,
                    purchases: 46,
                    survivor: SurvivorId::Rex,
                    loadout: None,
                    killed_by: MonsterId::GreaterWisp,
                    outcome: OutcomeId::Defeat,
                    stages: vec![
                        PlayerStageStats {
                            items: vec![
                                (Shuriken, 1),
                                (WeepingFungus, 1),
                                (MonsterTooth, 1),
                                (TougherTimes, 2),
                                (H3AD5Tv2, 1),
                                (Medkit, 1),
                                (OldGuillotine, 1),
                            ],
                            equipment: Some(TrophyHuntersTricorn).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Shuriken, 1),
                                (TougherTimes, 2),
                                (H3AD5Tv2, 1),
                                (Medkit, 1),
                                (PaulsGoatHoof, 1),
                                (RepulsionArmorPlate, 3),
                                (CautiousSlug, 1),
                                (ATGMissileMk1, 3),
                                (KjarosBand, 1),
                                (RunaldsBand, 1),
                            ],
                            equipment: Some(TrophyHuntersTricorn).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (WeepingFungus, 1),
                                (TougherTimes, 2),
                                (H3AD5Tv2, 1),
                                (Medkit, 1),
                                (PaulsGoatHoof, 1),
                                (RepulsionArmorPlate, 3),
                                (CautiousSlug, 1),
                                (ATGMissileMk1, 3),
                                (KjarosBand, 1),
                                (RunaldsBand, 1),
                                (ShippingRequestForm, 1),
                                (DiosBestFriend, 1),
                                (WaxQuail, 1),
                                (Mocha, 1),
                                (ItemScrapGreen, 2),
                            ],
                            equipment: Some(TrophyHuntersTricorn).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (WeepingFungus, 2),
                                (TougherTimes, 2),
                                (H3AD5Tv2, 1),
                                (Medkit, 1),
                                (PaulsGoatHoof, 1),
                                (RepulsionArmorPlate, 3),
                                (CautiousSlug, 1),
                                (ATGMissileMk1, 3),
                                (KjarosBand, 1),
                                (RunaldsBand, 2),
                                (ShippingRequestForm, 1),
                                (WaxQuail, 1),
                                (Mocha, 1),
                                (ItemScrapGreen, 3),
                                (DiosBestFriendConsumed, 1),
                                (Polylute, 1),
                                (StickyBomb, 1),
                                (TitanicKnurl, 1),
                                (RoseBuckler, 3),
                                (TriTipDagger, 5),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (WeepingFungus, 2),
                                (H3AD5Tv2, 1),
                                (Medkit, 2),
                                (PaulsGoatHoof, 1),
                                (RepulsionArmorPlate, 3),
                                (CautiousSlug, 1),
                                (ATGMissileMk1, 3),
                                (KjarosBand, 1),
                                (RunaldsBand, 2),
                                (ShippingRequestForm, 1),
                                (WaxQuail, 1),
                                (Mocha, 2),
                                (ItemScrapGreen, 3),
                                (DiosBestFriendConsumed, 1),
                                (Polylute, 1),
                                (StickyBomb, 2),
                                (TitanicKnurl, 1),
                                (RoseBuckler, 3),
                                (Needletick, 6),
                                (EnergyDrink, 1),
                                (EncrustedKey, 1),
                                (SaferSpaces, 3),
                                (Shuriken, 2),
                                (FuelCell, 1),
                                (Razorwire, 1),
                                (RedWhip, 1),
                                (WillOTheWisp, 1),
                                (EmpathyCores, 1),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: true,
                        },
                    ],
                },
            ],
            stages: vec![
                StageStats {
                    stage_id: EnvironmentId::TitanicPlains,
                    clock_at_end: mins_secs(14, 25).into(),
                    scaling_at_end: 10.into(),
                    mountain_shrines_hit: 0.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::AbandonedAqueduct,
                    clock_at_end: mins_secs(33, 36).into(),
                    scaling_at_end: 22.into(),
                    mountain_shrines_hit: 0.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::SulfurPools,
                    clock_at_end: mins_secs(45, 25).into(),
                    scaling_at_end: 34.into(),
                    mountain_shrines_hit: 0.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::SunderedGrove,
                    clock_at_end: mins_secs(62, 16).into(),
                    scaling_at_end: 53.into(),
                    mountain_shrines_hit: 2.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::SkyMeadow,
                    clock_at_end: None,
                    scaling_at_end: None,
                    mountain_shrines_hit: None,
                },
            ],
        },
        Run {
            timestamp: chrono::Utc
                .with_ymd_and_hms(2023, 11, 18, 8, 0, 44)
                .unwrap(),
            difficulty: DifficultyId::Eclipse1,
            players: vec![
                PlayerRun {
                    player_name: "sunrosa".into(),
                    time_alive: mins_secs(72, 19),
                    kills: 672,
                    minion_kills: 195,
                    deaths: 1,
                    damage_dealt: 4_577_353,
                    minion_damage_dealt: 1_106_349,
                    most_damage_dealt: 78_634,
                    damage_taken: 14_271,
                    highest_level: 26,
                    gold_collected: 211_065,
                    items_collected: 82,
                    stages_completed: 5,
                    purchases: 88,
                    survivor: SurvivorId::Bandit,
                    loadout: SurvivorLoadout::Bandit(BanditLoadout {
                        primary: BanditPrimaryId::Burst,
                        secondary: BanditSecondaryId::SerratedDagger,
                        special: BanditSpecialId::Desperado,
                    })
                    .into(),
                    killed_by: MonsterId::LunarGolem,
                    outcome: OutcomeId::Defeat,
                    stages: vec![
                        PlayerStageStats {
                            items: vec![
                                (Crowbar, 1),
                                (EnergyDrink, 1),
                                (Warbanner, 1),
                                (Medkit, 1),
                                (RepulsionArmorPlate, 1),
                                (ArmorPiercingRounds, 1),
                                (QueensGland, 1),
                                (Gasoline, 1),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Crowbar, 1),
                                (EnergyDrink, 1),
                                (Medkit, 1),
                                (RepulsionArmorPlate, 1),
                                (ArmorPiercingRounds, 1),
                                (QueensGland, 2),
                                (Gasoline, 2),
                                (IgnitionTank, 1),
                                (KjarosBand, 3),
                                (RunaldsBand, 2),
                                (DelicateWatch, 1),
                                (ItemScrapWhite, 1),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Crowbar, 2),
                                (EnergyDrink, 1),
                                (Medkit, 1),
                                (RepulsionArmorPlate, 1),
                                (ArmorPiercingRounds, 1),
                                (QueensGland, 2),
                                (Gasoline, 2),
                                (IgnitionTank, 1),
                                (KjarosBand, 3),
                                (RunaldsBand, 2),
                                (ItemScrapWhite, 1),
                                (LysateCell, 1),
                                (PaulsGoatHoof, 1),
                                (DelicateWatchBroken, 2),
                                (CautiousSlug, 1),
                                (HopooFeather, 1),
                                (DefenseNucleus, 1),
                                (DelicateWatch, 1),
                                (PowerElixir, 1),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Crowbar, 2),
                                (EnergyDrink, 1),
                                (Medkit, 1),
                                (RepulsionArmorPlate, 1),
                                (ArmorPiercingRounds, 1),
                                (QueensGland, 2),
                                (Gasoline, 3),
                                (IgnitionTank, 3),
                                (KjarosBand, 4),
                                (RunaldsBand, 3),
                                (LysateCell, 1),
                                (PaulsGoatHoof, 6),
                                (DelicateWatchBroken, 2),
                                (CautiousSlug, 1),
                                (HopooFeather, 1),
                                (DefenseNucleus, 1),
                                (DelicateWatch, 1),
                                (PowerElixir, 1),
                                (RustedKey, 1),
                                (WakeOfVultures, 1),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Crowbar, 2),
                                (EnergyDrink, 1),
                                (Medkit, 2),
                                (RepulsionArmorPlate, 1),
                                (ArmorPiercingRounds, 2),
                                (QueensGland, 2),
                                (Gasoline, 4),
                                (IgnitionTank, 3),
                                (KjarosBand, 6),
                                (RunaldsBand, 3),
                                (LysateCell, 2),
                                (PaulsGoatHoof, 6),
                                (DelicateWatchBroken, 2),
                                (CautiousSlug, 1),
                                (HopooFeather, 1),
                                (DefenseNucleus, 1),
                                (DelicateWatch, 1),
                                (WakeOfVultures, 1),
                                (EmptyBottle, 2),
                                (LeptonDaisy, 1),
                                (Chronobauble, 1),
                                (WaxQuail, 1),
                                (BundleOfFireworks, 1),
                                (TopazBrooch, 2),
                                (BerzerkersPauldron, 1),
                                (BackupMagazine, 1),
                                (RollOfPennies, 1),
                                (SaferSpaces, 1),
                                (StickyBomb, 1),
                                (VoidsentFlame, 1),
                                (RegeneratingScrap, 1),
                                (Infusion, 1),
                                (WarHorn, 2),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Crowbar, 5),
                                (EnergyDrink, 1),
                                (Medkit, 2),
                                (RepulsionArmorPlate, 1),
                                (ArmorPiercingRounds, 2),
                                (QueensGland, 2),
                                (Gasoline, 4),
                                (IgnitionTank, 3),
                                (KjarosBand, 8),
                                (RunaldsBand, 3),
                                (LysateCell, 2),
                                (PaulsGoatHoof, 6),
                                (DelicateWatchBroken, 3),
                                (CautiousSlug, 1),
                                (HopooFeather, 1),
                                (DefenseNucleus, 1),
                                (EmptyBottle, 2),
                                (LeptonDaisy, 1),
                                (Chronobauble, 1),
                                (WaxQuail, 1),
                                (BundleOfFireworks, 1),
                                (TopazBrooch, 2),
                                (BerzerkersPauldron, 1),
                                (BackupMagazine, 1),
                                (RollOfPennies, 1),
                                (SaferSpaces, 1),
                                (StickyBomb, 1),
                                (VoidsentFlame, 1),
                                (RegeneratingScrap, 1),
                                (Infusion, 1),
                                (WarHorn, 2),
                                (AlienHead, 1),
                            ],
                            equipment: Some(EccentricVase).into(),
                            died: true,
                        },
                    ],
                },
                PlayerRun {
                    player_name: "Veryveryoriginalname".into(),
                    time_alive: mins_secs(62, 6),
                    kills: 208,
                    minion_kills: 111,
                    deaths: 2,
                    damage_dealt: 349_382,
                    minion_damage_dealt: 532_046,
                    most_damage_dealt: 1_516,
                    damage_taken: 10_749,
                    highest_level: 27,
                    gold_collected: 169_910,
                    items_collected: 60,
                    stages_completed: 5,
                    purchases: 61,
                    survivor: SurvivorId::Bandit,
                    loadout: None,
                    killed_by: MonsterId::LunarGolem,
                    outcome: OutcomeId::Defeat,
                    stages: vec![
                        PlayerStageStats {
                            items: vec![
                                (OldWarStealthkit, 2),
                                (GhorsTome, 1),
                                (Ukulele, 1),
                                (CautiousSlug, 1),
                                (QueensGland, 1),
                                (Infusion, 2),
                                (StickyBomb, 1),
                            ],
                            equipment: Some(RadarScanner).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (OldWarStealthkit, 2),
                                (GhorsTome, 1),
                                (Ukulele, 1),
                                (SquidPolyp, 1),
                                (QueensGland, 2),
                                (Infusion, 2),
                                (StickyBomb, 1),
                                (BisonSteak, 1),
                                (TriTipDagger, 2),
                                (LensMakersGlasses, 1),
                                (HardlightAfterburner, 1),
                                (BundleOfFireworks, 1),
                                (Bandolier, 1),
                            ],
                            equipment: Some(RadarScanner).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Ukulele, 1),
                                (CautiousSlug, 1),
                                (QueensGland, 2),
                                (StickyBomb, 1),
                                (TriTipDagger, 2),
                                (HardlightAfterburner, 1),
                                (SaferSpaces, 1),
                                (RegeneratingScrap, 1),
                                (RoseBuckler, 1),
                                (PaulsGoatHoof, 1),
                                (SentientMeatHook, 1),
                                (ItemScrapWhite, 6),
                                (ItemScrapGreen, 8),
                            ],
                            equipment: Some(None),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Ukulele, 1),
                                (CautiousSlug, 1),
                                (QueensGland, 2),
                                (StickyBomb, 1),
                                (TriTipDagger, 2),
                                (HardlightAfterburner, 1),
                                (SaferSpaces, 1),
                                (RegeneratingScrap, 1),
                                (RoseBuckler, 1),
                                (PaulsGoatHoof, 5),
                                (SentientMeatHook, 1),
                                (ItemScrapWhite, 6),
                                (ItemScrapGreen, 9),
                                (SoldiersSyringe, 1),
                                (WakeOfVultures, 1),
                                (Chronobauble, 1),
                            ],
                            equipment: Some(DisposableMissileLauncher).into(),
                            died: false,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Ukulele, 1),
                                (CautiousSlug, 1),
                                (QueensGland, 2),
                                (StickyBomb, 1),
                                (TriTipDagger, 2),
                                (HardlightAfterburner, 1),
                                (SaferSpaces, 1),
                                (RegeneratingScrap, 1),
                                (RoseBuckler, 1),
                                (PaulsGoatHoof, 5),
                                (SentientMeatHook, 1),
                                (ItemScrapWhite, 6),
                                (ItemScrapGreen, 9),
                                (SoldiersSyringe, 1),
                                (WakeOfVultures, 1),
                                (Chronobauble, 1),
                            ],
                            equipment: Some(DisposableMissileLauncher).into(),
                            died: true,
                        },
                        PlayerStageStats {
                            items: vec![
                                (Ukulele, 1),
                                (CautiousSlug, 1),
                                (QueensGland, 2),
                                (StickyBomb, 1),
                                (TriTipDagger, 2),
                                (HardlightAfterburner, 1),
                                (SaferSpaces, 1),
                                (RoseBuckler, 1),
                                (PaulsGoatHoof, 5),
                                (SentientMeatHook, 1),
                                (SoldiersSyringe, 1),
                                (WakeOfVultures, 1),
                                (Chronobauble, 1),
                                (RegeneratingScrapConsumed, 1),
                                (AlienHead, 1),
                            ],
                            equipment: Some(DisposableMissileLauncher).into(),
                            died: true,
                        },
                    ],
                },
            ],
            stages: vec![
                StageStats {
                    stage_id: EnvironmentId::TitanicPlains,
                    clock_at_end: mins_secs(9, 22).into(),
                    scaling_at_end: 5.into(),
                    mountain_shrines_hit: 1.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::AbandonedAqueduct,
                    clock_at_end: mins_secs(19, 52).into(),
                    scaling_at_end: 13.into(),
                    mountain_shrines_hit: 1.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::SulfurPools,
                    clock_at_end: mins_secs(31, 23).into(),
                    scaling_at_end: 24.into(),
                    mountain_shrines_hit: 0.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::SirensCall,
                    clock_at_end: mins_secs(46, 55).into(),
                    scaling_at_end: 40.into(),
                    mountain_shrines_hit: 0.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::SkyMeadow,
                    clock_at_end: mins_secs(64, 10).into(),
                    scaling_at_end: 63.into(),
                    mountain_shrines_hit: 0.into(),
                },
                StageStats {
                    stage_id: EnvironmentId::Commencement,
                    clock_at_end: None,
                    scaling_at_end: None,
                    mountain_shrines_hit: 0.into(),
                },
            ],
        },
    ];

    let latest_run = runs.last().unwrap();

    let sunrosa_latest_run = latest_run
        .players
        .iter()
        .find(|x| x.player_name == "sunrosa")
        .unwrap();

    let sunrosa_latest_loadout = sunrosa_latest_run.loadout.as_ref().unwrap();

    println!("{:?}", sunrosa_latest_loadout);
}

// Second run items (incomplete)
//vec![
//    (Crowbar, 1),
//    (EnergyDrink, 1),
//    (Warbanner, 1),
//    (Medkit, 1),
//    (RepulsionArmorPlate, 1),
//    (ArmorPiercingRounds, 1),
//    (QueensGland, 1),
//    (Gasoline, 1),
//],
//vec![
//    (Crowbar, 1),
//    (EnergyDrink, 1),
//    (Medkit, 1),
//    (RepulsionArmorPlate, 1),
//    (ArmorPiercingRounds, 1),
//    (QueensGland, 2),
//    (Gasoline, 2),
//    (IgnitionTank, 1),
//    (KjarosBand, 3),
//    (RunaldsBand, 2),
//    (DelicateWatch, 1),
//    (ItemScrapWhite, 1),
//],
//vec![
//    (Crowbar, 2),
//    (EnergyDrink, 1),
//    (Medkit, 1),
//    (RepulsionArmorPlate, 1),
//    (ArmorPiercingRounds, 1),
//    (QueensGland, 2),
//    (Gasoline, 2),
//    (IgnitionTank, 1),
//    (KjarosBand, 3),
//    (RunaldsBand, 2),
//    (ItemScrapWhite, 1),
//    (LysateCell, 1),
//    (PaulsGoatHoof, 1),
//    (DelicateWatchBroken, 2),
//    (CautiousSlug, 1),
//    (HopooFeather, 1),
//    (DefenseNucleus, 1),
//    (DelicateWatch, 1),
//    (PowerElixir, 1),
//],

pub fn mins_secs(minutes: i64, seconds: i64) -> Duration {
    Duration::minutes(minutes) + Duration::seconds(seconds)
}
