mod data;
mod model;

use std::env::Vars;

use chrono::{Duration, TimeZone};
use data::{ItemId::*, *};
use model::*;

fn main() {
    // This takes fucking forever to type in. Please disinfect me.
    let run1 = Run {
        timestamp: chrono::Utc
            .with_ymd_and_hms(2023, 11, 18, 6, 31, 18)
            .unwrap(),
        difficulty: DifficultyId::Eclipse1,
        players: vec![
            PlayerRun {
                player_name: "sunrosa".into(),
                time_alive: mins_secs(81, 24),
                kills: 684,
                minion_kills: 57,
                deaths: 1,
                damage_dealt: 4_735_102,
                minion_damage_dealt: 361_520,
                most_damage_dealt: 10_386,
                damage_taken: 22_261,
                highest_level: 27,
                gold_collected: 263_813,
                items_collected: 108,
                stages_completed: 4,
                purchases: 128,
                survivor: SurvivorId::MulT,
                loadout: Some(SurvivorLoadout::MulT(MulTLoadout {
                    primary1: MulTPrimaryId::AutoNailgun,
                    primary2: MulTPrimaryId::AutoNailgun,
                    special: MulTSpecialId::PowerMode,
                })),
                killed_by: MonsterId::ElderLemurian,
                outcome: OutcomeId::Defeat,
                stages: vec![
                    PlayerStageStats {
                        items: vec![
                            (BackupMagazine, 1),
                            (StunGrenade, 1),
                            (CautiousSlug, 1),
                            (DelicateWatch, 1),
                            (IgnitionTank, 1),
                            (FocusCrystal, 2),
                            (LensMakersGlasses, 1),
                            (SquidPolyp, 1),
                            (BundleOfFireworks, 1),
                            (Gasoline, 1),
                            (OldGuillotine, 1),
                        ],
                        equipment: Some(VolcanicEgg),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (BackupMagazine, 1),
                            (StunGrenade, 1),
                            (CautiousSlug, 1),
                            (DelicateWatch, 1),
                            (IgnitionTank, 1),
                            (FocusCrystal, 2),
                            (LensMakersGlasses, 1),
                            (Gasoline, 1),
                            (SoldiersSyringe, 1),
                            (ATGMissileMk1, 3),
                            (RepulsionArmorPlate, 2),
                            (MiredUrn, 1),
                            (Ukulele, 1),
                            (SoulboundCatalyst, 1),
                        ],
                        equipment: Some(VolcanicEgg),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (BackupMagazine, 1),
                            (StunGrenade, 2),
                            (CautiousSlug, 1),
                            (DelicateWatch, 2),
                            (IgnitionTank, 1),
                            (LensMakersGlasses, 1),
                            (Gasoline, 1),
                            (SoldiersSyringe, 1),
                            (ATGMissileMk1, 3),
                            (RepulsionArmorPlate, 2),
                            (MiredUrn, 1),
                            (SoulboundCatalyst, 1),
                            (PaulsGoatHoof, 2),
                            (PocketICBM, 1),
                            (Polylute, 2),
                            (RustedKey, 1),
                            (SaferSpaces, 1),
                            (TriTipDagger, 1),
                            (ItemScrapGreen, 4),
                            (ItemScrapWhite, 6),
                        ],
                        equipment: Some(EccentricVase),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (StunGrenade, 2),
                            (CautiousSlug, 1),
                            (DelicateWatch, 3),
                            (IgnitionTank, 1),
                            (LensMakersGlasses, 1),
                            (Gasoline, 1),
                            (SoldiersSyringe, 2),
                            (ATGMissileMk1, 4),
                            (RepulsionArmorPlate, 2),
                            (MiredUrn, 1),
                            (SoulboundCatalyst, 1),
                            (PaulsGoatHoof, 2),
                            (PocketICBM, 1),
                            (Polylute, 2),
                            (SaferSpaces, 1),
                            (TriTipDagger, 5),
                            (ItemScrapGreen, 9),
                            (EnergyDrink, 1),
                            (RegeneratingScrap, 1),
                            (ShatteringJustice, 1),
                            (EncrustedKey, 1),
                            (PredatoryInstincts, 1),
                            (DeathMark, 1),
                        ],
                        equipment: Some(DisposableMissileLauncher),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (StunGrenade, 2),
                            (CautiousSlug, 1),
                            (IgnitionTank, 2),
                            (LensMakersGlasses, 1),
                            (Gasoline, 1),
                            (SoldiersSyringe, 2),
                            (ATGMissileMk1, 4),
                            (RepulsionArmorPlate, 2),
                            (MiredUrn, 1),
                            (SoulboundCatalyst, 1),
                            (PaulsGoatHoof, 3),
                            (PocketICBM, 1),
                            (Polylute, 2),
                            (SaferSpaces, 2),
                            (TriTipDagger, 5),
                            (ItemScrapGreen, 9),
                            (EnergyDrink, 1),
                            (RegeneratingScrap, 1),
                            (ShatteringJustice, 1),
                            (EncrustedKey, 1),
                            (PredatoryInstincts, 2),
                            (DeathMark, 1),
                            (LeptonDaisy, 3),
                            (PersonalShieldGenerator, 1),
                            (GhorsTome, 1),
                            (HopooFeather, 1),
                            (Chronobauble, 1),
                            (FocusCrystal, 1),
                            (WillOTheWisp, 1),
                            (EmpathyCores, 1),
                            (OldGuillotine, 1),
                            (Bandolier, 1),
                            (DelicateWatchBroken, 3),
                        ],
                        equipment: Some(DisposableMissileLauncher),
                        died: true,
                    },
                ],
            },
            PlayerRun {
                player_name: "Veryveryoriginalname".into(),
                time_alive: mins_secs(80, 48),
                kills: 502,
                minion_kills: 5,
                deaths: 2,
                damage_dealt: 3_180_003,
                minion_damage_dealt: 169_128,
                most_damage_dealt: 41_250,
                damage_taken: 51_357,
                highest_level: 27,
                gold_collected: 199_976,
                items_collected: 72,
                stages_completed: 4,
                purchases: 46,
                survivor: SurvivorId::Rex,
                loadout: None,
                killed_by: MonsterId::GreaterWisp,
                outcome: OutcomeId::Defeat,
                stages: vec![
                    PlayerStageStats {
                        items: vec![
                            (Shuriken, 1),
                            (WeepingFungus, 1),
                            (MonsterTooth, 1),
                            (TougherTimes, 2),
                            (H3AD5Tv2, 1),
                            (Medkit, 1),
                            (OldGuillotine, 1),
                        ],
                        equipment: Some(TrophyHuntersTricorn),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (Shuriken, 1),
                            (TougherTimes, 2),
                            (H3AD5Tv2, 1),
                            (Medkit, 1),
                            (PaulsGoatHoof, 1),
                            (RepulsionArmorPlate, 3),
                            (CautiousSlug, 1),
                            (ATGMissileMk1, 3),
                            (KjarosBand, 1),
                            (RunaldsBand, 1),
                        ],
                        equipment: Some(TrophyHuntersTricorn),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (WeepingFungus, 1),
                            (TougherTimes, 2),
                            (H3AD5Tv2, 1),
                            (Medkit, 1),
                            (PaulsGoatHoof, 1),
                            (RepulsionArmorPlate, 3),
                            (CautiousSlug, 1),
                            (ATGMissileMk1, 3),
                            (KjarosBand, 1),
                            (RunaldsBand, 1),
                            (ShippingRequestForm, 1),
                            (DiosBestFriend, 1),
                            (WaxQuail, 1),
                            (Mocha, 1),
                            (ItemScrapGreen, 2),
                        ],
                        equipment: Some(TrophyHuntersTricorn),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (WeepingFungus, 2),
                            (TougherTimes, 2),
                            (H3AD5Tv2, 1),
                            (Medkit, 1),
                            (PaulsGoatHoof, 1),
                            (RepulsionArmorPlate, 3),
                            (CautiousSlug, 1),
                            (ATGMissileMk1, 3),
                            (KjarosBand, 1),
                            (RunaldsBand, 2),
                            (ShippingRequestForm, 1),
                            (WaxQuail, 1),
                            (Mocha, 1),
                            (ItemScrapGreen, 3),
                            (DiosBestFriendConsumed, 1),
                            (Polylute, 1),
                            (StickyBomb, 1),
                            (TitanicKnurl, 1),
                            (RoseBuckler, 3),
                            (TriTipDagger, 5),
                        ],
                        equipment: Some(EccentricVase),
                        died: false,
                    },
                    PlayerStageStats {
                        items: vec![
                            (WeepingFungus, 2),
                            (H3AD5Tv2, 1),
                            (Medkit, 2),
                            (PaulsGoatHoof, 1),
                            (RepulsionArmorPlate, 3),
                            (CautiousSlug, 1),
                            (ATGMissileMk1, 3),
                            (KjarosBand, 1),
                            (RunaldsBand, 2),
                            (ShippingRequestForm, 1),
                            (WaxQuail, 1),
                            (Mocha, 2),
                            (ItemScrapGreen, 3),
                            (DiosBestFriendConsumed, 1),
                            (Polylute, 1),
                            (StickyBomb, 2),
                            (TitanicKnurl, 1),
                            (RoseBuckler, 3),
                            (Needletick, 6),
                            (EnergyDrink, 1),
                            (EncrustedKey, 1),
                            (SaferSpaces, 3),
                            (Shuriken, 2),
                            (FuelCell, 1),
                            (Razorwire, 1),
                            (RedWhip, 1),
                            (WillOTheWisp, 1),
                            (EmpathyCores, 1),
                        ],
                        equipment: Some(EccentricVase),
                        died: true,
                    },
                ],
            },
        ],
        stages: vec![
            StageStats {
                stage_id: EnvironmentId::TitanicPlains,
                clock_at_end: mins_secs(14, 25).into(),
                scaling_at_end: 10.into(),
                mountain_shrines_hit: 0.into(),
            },
            StageStats {
                stage_id: EnvironmentId::AbandonedAqueduct,
                clock_at_end: mins_secs(33, 36).into(),
                scaling_at_end: 22.into(),
                mountain_shrines_hit: 0.into(),
            },
            StageStats {
                stage_id: EnvironmentId::SulfurPools,
                clock_at_end: mins_secs(45, 25).into(),
                scaling_at_end: 34.into(),
                mountain_shrines_hit: 0.into(),
            },
            StageStats {
                stage_id: EnvironmentId::SunderedGrove,
                clock_at_end: mins_secs(62, 16).into(),
                scaling_at_end: 53.into(),
                mountain_shrines_hit: 2.into(),
            },
            StageStats {
                stage_id: EnvironmentId::SkyMeadow,
                clock_at_end: None.into(),
                scaling_at_end: None.into(),
                mountain_shrines_hit: None.into(),
            },
        ],
    };
}

// Second run items (incomplete)
//vec![
//    (Crowbar, 1),
//    (EnergyDrink, 1),
//    (Warbanner, 1),
//    (Medkit, 1),
//    (RepulsionArmorPlate, 1),
//    (ArmorPiercingRounds, 1),
//    (QueensGland, 1),
//    (Gasoline, 1),
//],
//vec![
//    (Crowbar, 1),
//    (EnergyDrink, 1),
//    (Medkit, 1),
//    (RepulsionArmorPlate, 1),
//    (ArmorPiercingRounds, 1),
//    (QueensGland, 2),
//    (Gasoline, 2),
//    (IgnitionTank, 1),
//    (KjarosBand, 3),
//    (RunaldsBand, 2),
//    (DelicateWatch, 1),
//    (ItemScrapWhite, 1),
//],
//vec![
//    (Crowbar, 2),
//    (EnergyDrink, 1),
//    (Medkit, 1),
//    (RepulsionArmorPlate, 1),
//    (ArmorPiercingRounds, 1),
//    (QueensGland, 2),
//    (Gasoline, 2),
//    (IgnitionTank, 1),
//    (KjarosBand, 3),
//    (RunaldsBand, 2),
//    (ItemScrapWhite, 1),
//    (LysateCell, 1),
//    (PaulsGoatHoof, 1),
//    (DelicateWatchBroken, 2),
//    (CautiousSlug, 1),
//    (HopooFeather, 1),
//    (DefenseNucleus, 1),
//    (DelicateWatch, 1),
//    (PowerElixir, 1),
//],

pub fn mins_secs(minutes: i64, seconds: i64) -> Duration {
    Duration::minutes(minutes) + Duration::seconds(seconds)
}
